### ISSUE TITLE
Update Donate Button to be Green CTA color

### ISSUE THREAD

**Issue by nicklacke** [ericcecchi/overnight-website#116]

**Comment by nicklacke** [comment]
I made the call to make it red, but on second glance it'd be better served being green to contrast all the red on the page.

**Comment by ericcecchi** [comment]
I'll make it #27C191 with an appropriate hover color.

**Comment by nicklacke** [comment]
Perfect!

On Thu, May 7, 2015 at 4:38 PM, Eric Cecchi notifications@github.com
wrote:

> I'll make it #27C191 with an appropriate hover color.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ericcecchi/overnight-website/issues/116#issuecomment-100026897
> .

## 

Nick Lacke
_Designer_

@nicklacke
www.nicklacke.com

Phone: 614.886.1106
