### ISSUE TITLE
Branding: Image Request

### ISSUE THREAD

**Issue by larrysprout** [ericcecchi/overnight-website#98]
Can we get one created for "Digital Library" as they want to launch this soon.

![screenshot 2015-05-03 05 35 31](https://cloud.githubusercontent.com/assets/9012172/7444701/56a87f4e-f156-11e4-9be7-5514a960018b.png)

**Comment by jwsid** [comment]
![bbr-digital-library](https://cloud.githubusercontent.com/assets/7341020/7444874/ee775ffa-f15d-11e4-8882-d05c46b387a0.jpg)
Image for digital library, I strongly suggest they don't use this until they have content to point it to! Things like teasing the release of new features is good for social media :smile:
